### ISSUE TITLE
`polyhorn new` doesn't work

### ISSUE THREAD

**Issue by simlay** [polyhorn/polyhorn#4]
Hey hey came across this project because it was linked to my iced-ios PR and figured I should give it a shot. This might be a known bug but I just wanted to write it in case it wasn't known.

* `cargo install polyhorn --git https://github.com/polyhorn/polyhorn` at current master (https://github.com/polyhorn/polyhorn/commit/f620b6ff4ca18469819cc5f36d2c003c2f48b9e9)
* `polyhorn new my-test-app` yields this for me: 

```
error[E0515]: cannot return reference to temporary value
  --> /Users/simlay/.cargo/registry/src/github.com-1ecc6299db9ec823/polyhorn-cli-0.3.2/src/android/targets.rs:27:9
   |
27 |            &[
   |  __________^-
   | | _________|
   | ||
28 | ||             Target::armeabi_v7a(),
29 | ||             Target::arm64_v8a(),
30 | ||             Target::x86(),
31 | ||             Target::x86_64(),
32 | ||         ]
   | ||         ^
   | ||_________|
   | |__________returns a reference to data owned by the current function
   |            temporary value created here

error: aborting due to previous error

For more information about this error, try `rustc --explain E0515`.
error: could not compile `polyhorn-cli`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
```

**Comment by cutsoy** [comment]
Hi and thanks! Yes, unfortunately Rust v1.48.0 is a bit more strict with references to constants. This used to work in <v1.48.0, but doesn't work anymore.

I fixed the issue in https://github.com/polyhorn/polyhorn-cli/commit/3b91d1d42ac487c585f02d0494edf4813f3bac8c. I also moved the CLI to its own Github repo and setup proper CI to make sure this doesn't happen again in the future.

The reason why it's not yet available through `cargo install`, is because I am still working on a better way to install the CLI so that it corresponds to the same version as the library in the `Cargo.toml` manifest of a Polyhorn project. I will probably finish that before the end of this week.

For now, (if possible), use `rustup` to install Rust v1.47.0. There are some other rough edges as well: for example, since we're cross-compiling, you'll need to [follow these steps](https://polyhorn.com/docs/workflow/editors) if you want rust-analyzer to be able to function properly.

Let me know if that works (if you have time)!

**Comment by cutsoy** [comment]
This should now work after upgrading to v0.4.1!

```sh
cargo install polyhorn --force
polyhorn new example
cd example
polyhorn run ios
```

Unfortunately, because Cargo compiles everything from source (the first time), this will take a few minutes.

When it's done installing, it will ask you which iOS simulator you want to run on and launch your new Polyhorn app!

**Comment by simlay** [comment]
Awesome!
